refactor(setDefaultLookAndFeel): fixme #292 Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: sun/swing/plaf/synth/SynthIcon […] Caused by: java.lang.ClassNotFoundException: sun.swing.plaf.synth.SynthIcon